### PR TITLE
Compatibility with Symfony/Translation v.5.0.x - type hints

### PR DESCRIPTION
**Pull request by mark-31**

### CODE REVIEW

**Comment by aleswita** [comment]
@mark-31 you have some problems with Symfony **5.0**? These type hints missing for compatibility between Symfony **4.4** and **5.0**

**Comment by mark-31** [comment]
Yes, from version 5.0 in symfony/translations are added parameter type declarations and it's incompatible with contributte/translations 5. After downgrade symfony/translations to version 4.4 it's ok, but with v. 5 application throws exceptions.

**Comment by mabar** [comment]
Parent parameter typehints can be widened or completely ommited from php 7.2+, are you still at php 7.1?

**Comment by mark-31** [comment]
Yes, php 7.1.31. Ok, I contact our server administrator for update php :) thx

**Comment by mabar** [comment]
Symfony 5 don't support php 7.1 anyway

**Comment by mark-31** [comment]
Hmm, it's true. I missed it, sorry :(

**Pull request closed without merging**
