### PR TITLE
Support for Yaml resources

### PR DESCRIPTION
**Pull request by tvaliasek**

### CODE REVIEW

**Comment by aleswita** [comment]
Why you overwritten **Symfony\Component\Translation\Loader\YamlFileLoader** only for change the exception instead of use it?

```neon
translation:
	loaders:
		yaml: Symfony\Component\Translation\Loader\YamlFileLoader
		yml: Symfony\Component\Translation\Loader\YamlFileLoader
```

**Comment by tvaliasek** [comment]
Sorry, my mistake, correct code is 

````neon
	loaders:
	    yaml: Contributte\Translation\Loaders\Yaml
	    yml: Contributte\Translation\Loaders\Yaml
````

**Comment by tvaliasek** [comment]
Yes, only because of tests and to maintain same structure like in neon loader.

**Comment by tvaliasek** [comment]
Maybe better documentation could be enough. Without reading the code, there are missing guides how to use locale resolvers and custom / other loaders.

**Comment by aleswita** [comment]
Neon loader exists in this package, because no exists in symfony package,

But i think good idea, update documentation about list of others symfony loaders:
```
array: Symfony\Component\Translation\Loader\ArrayLoader
csv: Symfony\Component\Translation\Loader\CsvFileLoader
dat: Symfony\Component\Translation\Loader\IcuDatFileLoader
res: Symfony\Component\Translation\Loader\IcuResFileLoader
ini: Symfony\Component\Translation\Loader\IniFileLoader
json: Symfony\Component\Translation\Loader\JsonFileLoader
mo: Symfony\Component\Translation\Loader\MoFileLoader
php: Symfony\Component\Translation\Loader\PhpFileLoader
po: Symfony\Component\Translation\Loader\PoFileLoader
ts: Symfony\Component\Translation\Loader\QtFileLoader
xlf: Symfony\Component\Translation\Loader\XliffFileLoader
yml: Symfony\Component\Translation\Loader\YamlFileLoader

**Comment by tvaliasek** [comment]
Yes, I will try write some in another PR.

**Comment by mabar** [comment]
Please, hold your horses. I received 14 emails, almost all about CI commits. All our packages have scripts predefined in Makefile (some with older structure in composer.json) and you can (and should) run them locally before commit. Even coding style fixer is available

**Comment by tvaliasek** [comment]
eeee… sorry

**Comment by mabar** [comment]
It's okay. Just wanted let you know you don't must wait for CI ;)

**Pull request closed without merging**
