### PR TITLE
Added cacheVary constructor parameter to Translator for parent Symfony\Component\Translation\Translator

### PR DESCRIPTION
**Pull request by kubomikita**

### CODE REVIEW

**Comment by aleswita** [comment]
Can you send 'translator' option in another PR?

**Comment by kubomikita** [comment]
Done.

**Comment by aleswita** [comment]
I'm fix the some issues in master with PHPStan, so now you can fix QA and PHPStan in your PR.

**Comment by aleswita** [comment]
tnx

**Pull request merged**
