### PR TITLE
new panel icon

### PR DESCRIPTION
**Pull request by emololftw**
*created new tracy panel icon with signature contributtes blue color 
*svg icon chars from 3k to 20k (svg file about 20kB)

spend few minutes in ps, full res icon can be found here: https://postimg.cc/jC4Nq2wg
What is your opinion?

### CODE REVIEW

**Comment by emololftw** [comment]
Panel preview:
image

**Comment by f3l1x** [comment]
I really like it 🤗

**Comment by aleswita** [comment]
Tnx

**Comment by emololftw** [comment]
Gentlemen, thank you for your responses. Next time I'll try to contribute something more useful. ♥

**Comment by spaze** [comment]
Btw, you can optimize SVGs with [SVGO](https://github.com/svg/svgo) ([GUI](https://jakearchibald.github.io/svgomg/)) to make them smaller, sometimes much smaller. I took the liberty and optimized the data and created #111.

**Pull request merged**
